version: '3.9'

networks:
  tasks-network:
    driver: bridge

services:
  task-database:
    container_name: task-database
    restart: unless-stopped
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    ports:
      - "9306:3306"
    networks:
      - tasks-network
    volumes: 
      - ./mysql:/var/lib/mysql

  webserver:
    image: nginx:alpine
    container_name: tasks-webserver
    volumes:
      - ./services:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    restart: unless-stopped
    tty: true
    ports:
      - "${PORT}:95"
      - "${PORT_UI}:96"
    networks:
      - tasks-network

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
    hostname: redis
    volumes:
      - ./redis-volume:/data
    networks:
      - tasks-network

  api-tasks:
    build:
      context: ./dockerfiles
      dockerfile: php8-1.dockerfile
    container_name: api-tasks
    volumes:
      - ./services/api-tasks:/var/www
    networks:
      - tasks-network
    command: /tmp/scripts/run.sh

  tasks-ui:
    build:
      context: ./dockerfiles
      dockerfile: php8-1.dockerfile
    container_name: tasks-ui
    volumes:
      - ./services/tasks-ui:/var/www
    networks:
      - tasks-network
    command: /tmp/scripts/run.sh